import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsString, Matches, MaxLength, MinLength } from 'class-validator';
import { PaymentMethod } from '@prisma/client';

// No amount/price/total field exists here: the sale total is always the sum
// of the TabItem snapshots, computed server-side.
export class CheckoutTabDto {
  @ApiProperty({ enum: PaymentMethod })
  @IsEnum(PaymentMethod)
  paymentMethod!: PaymentMethod;

  // Generated by the client once per checkout attempt (e.g. a UUID) and
  // re-sent on retries. Unique per tenant in the DB (orders_tenantId_idempotencyKey_key).
  @ApiProperty({ example: '6f1c2c1e-6d0e-4f4a-9a57-2f3a0a1b9c11' })
  @IsString()
  @MinLength(8)
  @MaxLength(100)
  @Matches(/^[A-Za-z0-9_-]+$/, { message: 'idempotencyKey deve conter apenas letras, números, "-" ou "_".' })
  idempotencyKey!: string;
}
